name: Build Test
run-name: ${{ github.actor }} pushed to ${{ github.ref_name }} branch, creating a new build

on:
  push:
    branches: [test/build, test/build2]

jobs:
  build:
    permissions: write-all
    name: Building the project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Post to slack
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          environment: 'dev'
          channel-id: ${{ variable.BUILD_BOT_SLACK_CHANNEL_ID }} }}
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BUILD_BOT_SLACK_BOT_TOKEN }} }}

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
        